can now define custom directories to save images and logs if imgur sends 'Invalid API key', default is used (built-in, no longer in .sour/key)

diff --git a/sour b/sour
--- a/sour
+++ b/sour
@@ -28,21 +28,30 @@ setDefaults() {
     # locations
     TMPDIR=${TMPDIR:-/tmp}
     location=$(mktemp -d "$TMPDIR/XXXXXXXXXXXXXX") ||\
-        { echo "ERROR could not create temporary directory" >&2; exit 1; }
-    working_dir="$PWD"
-    logdestfile="$HOME/.sour/log/$(date +"%m-%d-%y").log"
-    keyfile="$HOME/.sour/key"
+        { die "could not create temporary directory within /tmp"; }
+    rcfile="$HOME/.sourrc"
+
     datestamp="$(date +"%F_%H-%M-%S")"
+
+    default_key="4c9573275251eae9792bb783d807801c"
+    if [[ -s "$rcfile" ]]; then
+        source $rcfile
+        if [[ $key = '' ]]; then
+            key="$default_key"
+        fi
+    else
+        log_dir="$HOME/.sour/log"
+        screenshot_dir="$PWD"
+        key="$default_key"
+    fi
+    logdestfile="${log_dir}/$(date +"%m-%d-%y").log"
 
     # For createNeededFiles
     needed_files=("$logdestfile")
-    needed_dirs=("$HOME/.sour" "$HOME/.sour/log")
-    default_key='https://raw.github.com/wolfcore/sour/master/key'
+    needed_dirs=("$log_dir" $screenshot_dir)
 
     # for user options
     scrotcmd=''
-    #thumbcommand=''
-    #selectioncommand=''
     forum=0
     keep=0
     download=0
@@ -60,7 +69,9 @@ setDefaults() {
 
     # internal
     firstdone=0
+    # POSIX variable (getopts)
     OPTIND=1
+
 }
 
 # Files and directories needed for successful execution:
@@ -86,12 +97,6 @@ createNeededFiles() {
             fi
         fi
     done
-
-    # File exists and is a regular file, file exists and isn't empty
-    if [[ ! -f "$keyfile" || ! -s "$keyfile" ]]; then
-        curl $default_key -o $keyfile > /dev/null 2>&1
-    fi
-    source $keyfile
 }
 
 moveTo() {
@@ -103,7 +108,7 @@ moveTo() {
         if ! mv "$file" "$dest" > /dev/null 2>&1; then
             # Try sending the file to home dir.
             if [[ ! $dest == $HOME ]]; then
-                echo "failed to move $file to $dest...sending to $HOME" >&2
+                non_fatal "failed to move $file to $dest...sending to $HOME"
                 moveTo $file $HOME
             else
                 die "failed to move $file to $dest"
@@ -116,16 +121,16 @@ removeTemporaries() {
     if ((keep)); then
         if ((existing)); then
             if ((forum)); then
-                moveTo "$smallimagelocation" "$working_dir"
+                moveTo "$smallimagelocation" "$screenshot_dir"
             fi
 
         # existing == false, and keep any images created
         else
             if ((forum)); then
-                moveTo "$smallimagelocation" "$working_dir"
+                moveTo "$smallimagelocation" "$screenshot_dir"
             fi
             # Still need to move the regular image:
-            moveTo "$largeimagelocation" "$working_dir"
+            moveTo "$largeimagelocation" "$screenshot_dir"
         fi
 
     # keep == false, remove everything
@@ -140,8 +145,11 @@ setTraps() {
 
 die() {
     echo "ERROR: $@" >&2
-    echo '' | xclip
     exit 1
+}
+
+non_fatal() {
+    echo "NON-FATAL: $@" >&2
 }
 
 sendOutput() {
@@ -162,9 +170,6 @@ uploadFile() {
 
 parseAndReturn() {
     local resp="$@"
-    if [[ $resp = *error* ]]; then
-        die "error found in response"
-    fi
 
     local url=${resp#*<original_image>}
     url=${url%</original_image>*}
@@ -189,6 +194,15 @@ parseAndReturn() {
     
 makeImageUpload() {
     largeimageresponse=$(uploadFile "$largeimagelocation")
+    if [[ $largeimageresponse = *error* ]]; then
+        if [[ $largeimageresponse = *1004* ]]; then
+            non_fatal "Key defined in $rcfile is invalid... using default_key"
+            key="$default_key"
+            largeimageresponse=$(uploadFile "$largeimagelocation")
+        else
+            die "error found in response"
+        fi
+    fi
     parseAndReturn "$largeimageresponse"
     checkAndMakeThumb
 }
